# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package UserLib;
use base qw(Exporter);
use base qw(DynaLoader);
package UserLibc;
bootstrap UserLib;
package UserLib;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package UserLib;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package UserLib;

*BPP = *UserLibc::BPP;
*ODFN = *UserLibc::ODFN;
*OPF = *UserLibc::OPF;
*ODFSmA = *UserLibc::ODFSmA;
*SDN11_2_DllDp2 = *UserLibc::SDN11_2_DllDp2;
*Torrey = *UserLibc::Torrey;
*Torrey1 = *UserLibc::Torrey1;
*GAUSS = *UserLibc::GAUSS;
*GAUSS1 = *UserLibc::GAUSS1;
*GAULOR = *UserLibc::GAULOR;
*GLmix = *UserLibc::GLmix;
*LORTZN = *UserLibc::LORTZN;
*ROUSE = *UserLibc::ROUSE;
*ROUSE123 = *UserLibc::ROUSE123;
*ECD_poli = *UserLibc::ECD_poli;
*CED_poli = *UserLibc::CED_poli;
*RMTDnum = *UserLibc::RMTDnum;
*RotVold = *UserLibc::RotVold;
*RNordio = *UserLibc::RNordio;
*CROSSRELAX = *UserLibc::CROSSRELAX;
*iT1ISpara = *UserLibc::iT1ISpara;
*iT1inISpara = *UserLibc::iT1inISpara;
*CompElliptic1 = *UserLibc::CompElliptic1;
*EllipticF = *UserLibc::EllipticF;
*EllipticE = *UserLibc::EllipticE;
*HavNeg = *UserLibc::HavNeg;

# ------- VARIABLE STUBS --------

package UserLib;

1;
